name: C# CI

permissions:
  contents: read

on:
  push:
    branches: [ '*', '*/*' ]

jobs:
  test:
    name: Test for C# ${{ matrix.dotnetver }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        dotnetver: ['8.0.x', '9.0.x', '10.0.x']
        os: [ubuntu-latest, windows-latest, macos-latest]      
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: ${{ matrix.dotnetver }}
      - run: ./build.sh test
